### ISSUE TITLE
Missing rationale

### ISSUE THREAD

**Issue by cyberphone** [w3c/merchant-validation#1]
https://github.com/w3c/payment-request/issues/927#issuecomment-698105005

**Comment by marcoscaceres** [comment]
Not sure what additional text you are looking for @cyberphone? The rationale is at:
https://w3c.github.io/merchant-validation/#merchant-validation

And the actual details are outside the scope of the document.

**Comment by cyberphone** [comment]
I understand what the solution does but not what important problem it may solve.

**Comment by marcoscaceres** [comment]
Ah right. It's documenting how `MerchantValidationEvent`s works.

**Comment by cyberphone** [comment]
No, it is documenting why you need it.
